#!/bin/bash
#PBS -P xc0
#PBS -a 0600
#PBS -q normal
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l walltime=02:00:00
#PBS -l jobfs=100GB

module load cdo

cd /home/603/pl5189/github/fire-data-processing
/g/data1/xc0/software/conda-envs/rs3/bin/python update_flammability.py -y $year -t $tile -dst /g/data/ub8/au/FMC/c6/flam_c6_${year}_${tile}.nc -tmp $PBS_JOBFS

cd /home/603/pl5189/github/fire-data-processing/raijin_tasks
qsub -v year=${year},tile=${tile} flam_rec.qsub
