#!/bin/bash
#PBS -P ai53
#PBS -a 1800
#PBS -q normal
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l walltime=02:00:00
#PBS -l jobfs=100GB

module load cdo

cd /home/603/pl5189/github/fire-data-processing
/g/data1/xc0/software/conda-envs/rs3/bin/python update_fmc_mosaic.py -y $year -dst /g/data/ub8/au/FMC/c6/mosaics/fmc_c6_${year}.nc -tmp $PBS_JOBFS
chmod -R a+r /g/data/ub8/au/FMC/c6

cd /home/603/pl5189/fire-data-processing/raijin_tasks
qsub -v year=${year} fmc_mosaic_rec.qsub
