#!/bin/bash
#PBS -P ac76
#PBS -q normal
#PBS -l ncpus=1
#PBS -l mem=8GB
#PBS -l walltime=03:00:00
#PBS -l storage=gdata/ub8+gdata/xc0
#PBS -l jobfs=100GB

module load cdo
cd /home/603/pl5189/github/fire-data-processing
/g/data/xc0/software/conda-envs/rs3/bin/python update_flammability_mosaic.py -y $year -dst /g/data/ub8/au/FMC/2020/mosaics/flam_c6_${year}.nc -tmp $PBS_JOBFS
chmod -R a+r /g/data/ub8/au/FMC/2020
