#!/bin/bash
#PBS -P ac76
#PBS -q normal
#PBS -l storage=gdata/xc0+gdata/u39+gdata/ub8
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l walltime=20:00:00
#PBS -l jobfs=100GB

module load cdo
cd /g/data/xc0/user/scortechini/github/fire-data-processing
/g/data/xc0/software/conda-envs/rs3/bin/python update_flammability.py -y $year -t $tile -dst /g/data/xc0/user/scortechini/correct_tiles/flam/flam_c6_${year}_${tile}.nc -tmp $PBS_JOBFS
