#!/bin/bash
#PBS -P xc0
#PBS -q express
#PBS -l ncpus=8
#PBS -l mem=16GB
#PBS -l walltime=03:00:00
module load netcdf
module load nco
cd /g/data1a/xc0/user/ali/code/fire_deciles
/g/data/xc0/software/python/miniconda3/bin/python3 05_zonal_statistics_merge_to_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp LGA fmc_mean
cd /g/data1a/xc0/user/ali/code/fire_deciles
/g/data/xc0/software/python/miniconda3/bin/python3 05_zonal_statistics_merge_to_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp FWA fmc_mean
