#!/bin/bash
#PBS -P fo65
#PBS -q normal
#PBS -l storage=gdata/xc0+gdata/u39
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l walltime=04:00:00
#PBS -l jobfs=100GB

module load cdo
cd /g/data/xc0/user/scortechini/github/fire-data-processing
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/update_fmc_different_mcd43a4_path.py -d $year -t $tile -dst  /g/data/xc0/user/scortechini/israel/fmc_c6_${tile}.nc -tmp $PBS_JOBFS
