#!/bin/bash
#PBS -P bk75
#PBS -a 1815
#PBS -q normal
#PBS -l storage=gdata/xc0+gdata/ub8
#PBS -l ncpus=1
#PBS -l mem=48GB
#PBS -l walltime=15:00:00

module load netcdf
module load nco

cd /g/data/xc0/user/scortechini/github/fire-data-processing/deciles/



/g/data/xc0/software/python/miniconda3/bin/python3 03_calc_single_year_deciles.py fmc_mean /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp $year

/g/data/xc0/software/python/miniconda3/bin/python3 04_zonal_statistics_org_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp fmc_mean $year FWA
/g/data/xc0/software/python/miniconda3/bin/python3 04_zonal_statistics_deciles.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp fmc_mean $year FWA
/g/data/xc0/software/python/miniconda3/bin/python3 05_zonal_statistics_deciles_merge_to_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp FWA fmc_mean
/g/data/xc0/software/python/miniconda3/bin/python3 05_zonal_statistics_deciles_merge_to_nc_org_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp FWA fmc_mean

/g/data/xc0/software/python/miniconda3/bin/python3 04_zonal_statistics_deciles.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp fmc_mean $year LGA
/g/data/xc0/software/python/miniconda3/bin/python3 04_zonal_statistics_org_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp fmc_mean $year LGA
/g/data/xc0/software/python/miniconda3/bin/python3 05_zonal_statistics_deciles_merge_to_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp LGA fmc_mean
/g/data/xc0/software/python/miniconda3/bin/python3 05_zonal_statistics_deciles_merge_to_nc_org_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp LGA fmc_mean


/g/data/xc0/software/python/miniconda3/bin/python3 03_calc_single_year_deciles.py flammability /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp $year

/g/data/xc0/software/python/miniconda3/bin/python3 04_zonal_statistics_deciles.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp flammability $year FWA
/g/data/xc0/software/python/miniconda3/bin/python3 04_zonal_statistics_org_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp flammability $year FWA
/g/data/xc0/software/python/miniconda3/bin/python3 05_zonal_statistics_deciles_merge_to_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp FWA flammability
/g/data/xc0/software/python/miniconda3/bin/python3 05_zonal_statistics_deciles_merge_to_nc_org_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp FWA flammability

/g/data/xc0/software/python/miniconda3/bin/python3 04_zonal_statistics_deciles.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp flammability $year LGA
/g/data/xc0/software/python/miniconda3/bin/python3 04_zonal_statistics_org_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp flammability $year LGA
/g/data/xc0/software/python/miniconda3/bin/python3 05_zonal_statistics_deciles_merge_to_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp LGA flammability
/g/data/xc0/software/python/miniconda3/bin/python3 05_zonal_statistics_deciles_merge_to_nc_org_nc.py /g/data/xc0/project/FMC_Australia/calc_deciles/data/temp LGA flammability



cd /g/data/xc0/user/scortechini/github/fire-data-processing/gadi_tasks/jobs_reports
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/gadi_tasks/au_recurrent_qsubs/au_stats_and_deciles_qsub_rec.py
