#!/bin/bash
#PBS -P mr51
#PBS -q normal
#PBS -l storage=gdata/xc0+gdata/u39+gdata/ub8+scratch/mr51
#PBS -l ncpus=1
#PBS -l mem=10GB
#PBS -l walltime=48:00:00
#PBS -l jobfs=100GB

module load cdo

/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/deciles/zonalstats_zonal_stats_relative.py -decfolder /g/data/ub8/au/FMC/stats -vegmaskfolder /g/data/ub8/au/FMC/intermediary_files/vegetation_mask -areafolder /g/data/ub8/au/FMC/intermediary_files/areal_classifications -area fwa -var flam -ystart 2001 -yend 2023 -outfolder /scratch/mr51/gs3146 -tmpfolder $PBS_JOBFS
