module load cdo

/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2001 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2001.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2002 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2002.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2003 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2003.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2004 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2004.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2005 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2005.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2007 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2007.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2008 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2008.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2009 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2009.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2010 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2010.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2011 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2011.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2012 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2012.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2013 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2013.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2014 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2014.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2015 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2015.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2016 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2016.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2017 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2017.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2018 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2018.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2019 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2019.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_fmc_files.py -y 2020 -dst /g/data/ub8/au/FMC/perf_prof_test/fmc_c6_2020.nc

/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2001 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2001.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2002 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2002.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2003 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2003.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2004 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2004.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2005 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2005.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2007 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2007.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2008 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2008.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2009 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2009.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2010 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2010.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2011 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2011.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2012 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2012.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2013 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2013.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2014 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2014.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2015 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2015.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2016 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2016.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2017 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2017.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2018 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2018.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2019 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2019.nc
/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/chunk_flam_files.py -y 2020 -dst /g/data/ub8/au/FMC/perf_prof_test/flam_c6_2020.nc
