#!/bin/bash
#PBS -P bk75
#PBS -a 1900
#PBS -q normal
#PBS -l storage=gdata/xc0+gdata/u39+gdata/ub8
#PBS -l ncpus=1
#PBS -l mem=6GB
#PBS -l walltime=20:00:00
#PBS -l jobfs=100GB

module load cdo
cd /g/data/xc0/user/scortechini/github/fire-data-processing
/g/data/xc0/software/conda-envs/rs3/bin/python update_fmc.py -d $year -t $tile -dst /g/data/ub8/au/FMC/tiles/fmc_c61_${year}_${tile}.nc -tmp $PBS_JOBFS


cd /g/data/xc0/user/scortechini/github/fire-data-processing/gadi_tasks/jobs_reports
qsub -v year=${year},tile=${tile} /g/data/xc0/user/scortechini/github/fire-data-processing/gadi_tasks/au_recurrent_qsubs/au_fmc_tiles_rec.qsub
