#!/bin/bash
#PBS -P mr51
#PBS -a 0100
#PBS -q normal
#PBS -l storage=gdata/xc0+gdata/u39+gdata/ub8
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l walltime=01:00:00
#PBS -l jobfs=100GB

module load cdo
cd /g/data/xc0/user/scortechini/github/fire-data-processing/main_lfmc_flam
/g/data/xc0/software/conda-envs/rs3/bin/python update_flammability.py -y $year -t $tile -dst /g/data/ub8/au/FMC/tiles/flam_c6_${year}_${tile}.nc -tmp $PBS_JOBFS

cd /g/data/xc0/user/scortechini/github/fire-data-processing/gadi_tasks/jobs_reports
qsub -v year=${year},tile=${tile} /g/data/xc0/user/scortechini/github/fire-data-processing/gadi_tasks/au_recurrent_qsubs/au_flam_tiles_rec.qsub

