#!/bin/bash
#PBS -P mr51
#PBS -a 0300
#PBS -q normal
#PBS -l storage=gdata/xc0+gdata/u39+gdata/ub8
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l walltime=02:00:00
#PBS -l jobfs=100GB

module load cdo
cd /g/data/xc0/user/scortechini/github/fire-data-processing/deciles
/g/data/xc0/software/conda-envs/rs3/bin/python zonalstats_update_rank_with_deciles.py -decfolder /g/data/ub8/au/FMC/intermediary_files/deciles_arrays -mosfolder /g/data/ub8/au/FMC/mosaics -var $var -ystart 2023 -yend 2023 -outfolder /g/data/ub8/au/FMC/stats -tmpfolder $PBS_JOBFS


cd /g/data/xc0/user/scortechini/github/fire-data-processing/gadi_tasks/jobs_reports
qsub -v var=${var} /g/data/xc0/user/scortechini/github/fire-data-processing/gadi_tasks/au_recurrent_qsubs/rank_with_deciles_rec.qsub
