#!/bin/bash
#PBS -P mr51
#PBS -a 0500
#PBS -q normal
#PBS -l storage=gdata/xc0+gdata/u39+gdata/ub8
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l walltime=02:00:00
#PBS -l jobfs=100GB

module load cdo
cd /g/data/xc0/user/scortechini/github/fire-data-processing/deciles

/g/data/xc0/software/conda-envs/rs3/bin/python zonalstats_zonal_stats_absolute.py -mosfolder /g/data/ub8/au/FMC/mosaics -vegmaskfolder /g/data/ub8/au/FMC/intermediary_files/vegetation_mask -areafolder /g/data/ub8/au/FMC/intermediary_files/areal_classifications -area $area -var $var -ystart 2023 -yend 2023 -outfolder /g/data/ub8/au/FMC/stats/zonal_stats -tmpfolder $PBS_JOBFS

cd /g/data/xc0/user/scortechini/github/fire-data-processing/gadi_tasks/jobs_reports
qsub -v area=${area},var=${var} /g/data/xc0/user/scortechini/github/fire-data-processing/gadi_tasks/au_recurrent_qsubs/zonal_stats_abs_rec.qsub
